<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    public function getUnsent()
    {
        $qb = $this->createQueryBuilder('n')
            ->select('n')
            ->where('n.sent = false')
            ;

        return $qb->getQuery()->iterate();
    }
}
